---
# tasks file for diario-opositor-bot
- name: create user
  user: name={{bot_user}} system=yes

- name: Create directory for the bot
  file:
    state: directory
    path: "{{item}}"
    mode: 0755
    owner: '{{bot_user}}'
    group: '{{bot_user}}'
  with_items:
    - "{{project_folder}}/"
    - "{{project_folder}}/configs"
    - "{{project_folder}}/database"
    - "{{project_folder}}/reddit"
    - "{{project_folder}}/rss"

- name: Copy python files
  copy: src=diario-opositor-bot/ dest={{project_folder}}/ mode=755

- name: Transforming the bot start script into executable
  file:
    dest: '{{project_folder}}/diario_opositor_bot.py'
    mode: a+x
    owner: '{{bot_user}}'
    group: '{{bot_user}}'

- name: Install python packages
  pip:
    requirements: '{{project_folder}}/requirements.txt'

- name: Generate signature.conf
  copy:
    dest: '{{project_folder}}/signature.conf'
    content: '{{signature}}'
    force: yes
    group: '{{bot_user}}'
    owner: '{{bot_user}}'
    mode: 755

- name: Copy dob service
  template: src=dob.service dest=/usr/lib/systemd/system/dob.service

- name: Enable dob
  service: name=dob.service enabled=yes state=started
