---
# tasks file for diario-opositor-bot
- name: create user
  user: name=dob system=yes

- name: Create directory for the bot
  file:
    state: directory
    path: "{{item}}"
    mode: 0755

  with_items:
    - "{{project_folder}}/"
    - "{{project_folder}}/configs"
    - "{{project_folder}}/database"
    - "{{project_folder}}/reddit"
    - "{{project_folder}}/rss"

- name: Copy python files
  copy: src=diario-opositor-bot/ dest={{project_folder}}/ mode=755

- name: Transforming the bot start script into executable
  file: dest={{project_folder}}/diario_opositor_bot.py mode=a+x

- name: Install python packages
  pip:
    requirements: '{{project_folder}}/requirements.txt'

- name: Create python output
  file:
    content: ""
    dest: "{{project_folder}}/bot_log.txt"
    mode: 755
    force: no
    owner: dob
    group: dob
    state: touch

- name: copy dob service
  template: src=dob.service dest=/usr/lib/systemd/system/dob.service

- name: enable dob
  service: name=dob.service enabled=yes state=started
